# .readthedocs.yaml
version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install pdm
      - pdm install -G docs
    pre_build:
      # Render Quarto files to Markdown for MkDocs
      - pdm run quarto render docs-src --output docs
      # Rename -gfm.md files to .md
      - find docs -name "*-gfm.md" -exec sh -c 'mv "$0" "$(echo "$0" | sed "s/-gfm//")"' {} \;
